name: docker-build-pr

on:
  pull_request:
    branches: [ main ]


jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: provarepro

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Define container info
        id: info
        run: |
          git fetch origin ${{ github.head_ref }}
          SW_NAME=$(echo ${GITHUB_REPOSITORY##*/} | sed 's/ *$//g')
          DOCKER_SW_NAME=${SW_NAME,,}
          COMMIT_MESSAGE=$(git log --pretty=format:%s FETCH_HEAD | head -1)
          SW_TAG=${COMMIT_MESSAGE#*"Build docker:"}
          if [[ "${COMMIT_MESSAGE}" != "${SW_TAG}" ]]; then
            SW_TAG=$(echo ${SW_TAG%%,*} | sed 's/ *$//g')
            echo "SW_TAG: ${SW_TAG}"
            DOCKERFILEPATH=$(find . -name "${SW_TAG}.dockerfile")
            CONTEXT_PATH=${DOCKERFILEPATH%/*}
            echo "CTX: ${CONTEXT_PATH}"
            IMAGE_NAME="${DOCKER_ORG}/${DOCKER_SW_NAME}:${SW_TAG}"
            echo "IMG: ${IMAGE_NAME}"

            echo ::set-output name=context_path::${CONTEXT_PATH}
            echo ::set-output name=dockerfile::"${DOCKERFILEPATH}"
            echo ::set-output name=image_name::${IMAGE_NAME}
          else
            echo ::set-output name=skip::true
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.info.outputs.skip != 'true' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ steps.info.outputs.skip != 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ steps.info.outputs.skip != 'true' }}
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ steps.info.outputs.context_path }}
          file: ${{ steps.info.outputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.info.outputs.image_name }}
          cache-from: ${{ steps.info.outputs.image_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ steps.info.outputs.skip != 'true' }}
